P002_Deltares/P002_Deltares/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('PA001_Deltares.urls')),
    path('deltares/', include('PA002_Deltares.urls')),
    path('gppd/', include('PA003_GPP_Datos.urls')),
    path('result/', include('PA004_Result.urls')), 
    path('maps/', include('PA005_Maps.urls')),    
    path('links/', include('PA006_Links.urls')), 
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

P002_Deltares/PA005_Maps/urls.py
from django.urls import path
from PA005_Maps import views

urlpatterns = [
    path('', views.datos, name='Maps'),                 
]

P002_Deltares/PA001_Deltares/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey and OneToOneField has `on_delete` set to the desired behavior
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.contrib.gis.db import models

class Pa001PostgisAfricanriver(models.Model):
    id = models.BigAutoField(primary_key=True)
    mrbid = models.IntegerField()
    riverbasin = models.CharField(max_length=100)
    river = models.CharField(max_length=100)
    sea = models.CharField(max_length=100)
    ocean = models.CharField(max_length=100)
    shapelen = models.FloatField()
    mline = models.MultiLineStringField()

    class Meta:
        managed = False
        db_table = 'PA001_PostGis_africanriver'

class Pa001PostgisAfricabasin(models.Model):
    id = models.BigAutoField(primary_key=True)
    mrbid = models.IntegerField()
    riverbasin = models.CharField(max_length=100)
    sea = models.CharField(max_length=100)
    ocean = models.CharField(max_length=100)
    shapelen = models.FloatField()
    mpoly = models.MultiPolygonField()

    class Meta:
        managed = False
        db_table = 'PA001_PostGis_africabasin'

class Pa001PostgisFunción(models.Model):
    id = models.BigAutoField(primary_key=True)
    comando = models.CharField(max_length=6)
    created = models.DateTimeField(auto_now_add=True , null = False, blank=False)
    updated = models.DateTimeField(auto_now_add=True , null = False, blank=False)

    class Meta:
        managed = False
        db_table = 'PA001_PostGis_función'


class Pa001PostgisGppd(models.Model):
    id = models.BigAutoField(primary_key=True)
    id_gpp = models.CharField(max_length=30)
    description = models.CharField(max_length=250)
    user = models.CharField(max_length=150)
    created = models.DateTimeField(auto_now_add=True , null = False, blank=False)
    updated = models.DateTimeField(auto_now_add=True , null = False, blank=False)

    class Meta:
        managed = False
        db_table = 'PA001_PostGis_gppd'


class Pa001PostgisGppdoption(models.Model):
    id = models.BigAutoField(primary_key=True)
    unit = models.CharField(max_length=3)
    id_option = models.CharField(max_length=30)
    outputdir = models.CharField(max_length=255)
    meteo_file = models.CharField(max_length=100)
    outlier = models.BooleanField()
    ustar = models.BooleanField()
    ustar_non_annual = models.BooleanField()
    partition = models.BooleanField()
    fill = models.BooleanField()
    fluxerr = models.BooleanField()
    daily_gpp = models.BooleanField()
    climatological_footprint = models.BooleanField()
    calculated_ffp = models.BooleanField()
    vegetation_indices = models.BooleanField()
    environmental_variables_station = models.BooleanField()
    environmental_variables_satellite = models.BooleanField()
    tower_observations = models.BooleanField()
    df_rainfall_station_switch = models.BooleanField()
    df_meteo_station_switch = models.BooleanField()
    df_rainfall_chirps_switch = models.BooleanField()
    df_temp_modis_switch = models.BooleanField()
    df_meteo_tower_switch = models.BooleanField()
    correlation_analysis = models.BooleanField()
    correlation_analysis_simple = models.BooleanField()
    rei_gpp_switch = models.BooleanField()
    fal_gpp_switch = models.BooleanField()
    las_gpp_switch = models.BooleanField()
    calibration_validation = models.BooleanField()
    modis_analysis = models.BooleanField()
    timeseries_thirty = models.BooleanField()
    timeseries_fifteen = models.BooleanField()
    mapping_gpp = models.BooleanField()
    classification_maps = models.BooleanField()
    maps_from_features = models.BooleanField()
    mapping_gpp_thirty = models.BooleanField()
    mapping_gpp_fifteen = models.BooleanField()
    export_maps_to_drive = models.BooleanField()
    timeformat = models.CharField(max_length=20)
    sep = models.CharField(max_length=1)
    skiprows = models.CharField(max_length=4)
    undef = models.FloatField()
    swthr = models.FloatField()
    outputfile = models.CharField(max_length=20)
    outputname = models.CharField(max_length=40)
    outundef = models.BooleanField()
    outflagcols = models.BooleanField()
    carbonflux = models.CharField(max_length=10)
    remove_sw_in = models.BooleanField()
    nscan = models.IntegerField()
    nfill = models.IntegerField()
    z = models.IntegerField()
    deriv = models.IntegerField()
    ustarmin = models.FloatField()
    nboot = models.IntegerField()
    plateaucrit = models.FloatField()
    seasonout = models.BooleanField()
    applyustarflag = models.BooleanField()
    sw_dev = models.FloatField()
    ta_dev = models.FloatField()
    vpd_dev = models.FloatField()
    longgap = models.IntegerField()
    nogppnight = models.BooleanField()
    carbonfluxlimit = models.IntegerField()
    respirationlimit = models.IntegerField()
    rolling_window_gpp = models.IntegerField()
    rolling_center_gpp = models.BooleanField()
    rolling_min_periods = models.IntegerField()
    altitude = models.FloatField()
    latitude = models.FloatField()
    longitude = models.FloatField()
    canopy_height = models.FloatField()
    displacement_height = models.FloatField()
    roughness_lenght = models.FloatField()
    instrument_height_anenometer = models.FloatField()
    instrument_height_gas_analyzer = models.FloatField()
    projection_site_utm_zone = models.IntegerField()
    boundary_layer_height = models.IntegerField()
    domaint_var = models.CharField(max_length=30)
    nxt_var = models.IntegerField()
    rst_var = models.CharField(max_length=20)
    max_cloud_coverage = models.IntegerField()
    crs = models.CharField(max_length=30)
    ndvimask = models.IntegerField()
    mndvimask = models.IntegerField()
    rolling_window_ev_meteo = models.IntegerField()
    rolling_window_ev_meteo_sat = models.IntegerField()
    rolling_window_gpp_modis = models.IntegerField()
    precipitation_data = models.CharField(max_length=20)
    scale_satellite_data = models.IntegerField()
    feature_collection = models.CharField(max_length=50)
    ecosystem_extension = models.IntegerField()
    number_clusters = models.IntegerField()
    training_scale = models.IntegerField()
    training_dataset = models.IntegerField()
    scale_getregion = models.IntegerField()
    vector_scale = models.IntegerField()
    vector_scalex = models.IntegerField()
    created = models.DateTimeField(auto_now_add=True , null = False, blank=False)
    updated = models.DateTimeField(auto_now_add=True , null = False, blank=False)

    class Meta:
        managed = False
        db_table = 'PA001_PostGis_gppdoption'


class Pa001PostgisImagefile(models.Model):
    id = models.BigAutoField(primary_key=True)
    id_gpp = models.CharField(max_length=30)
    f_name = models.CharField(max_length=255)
    image_texto = models.CharField(max_length=255)
    image = models.ImageField(upload_to="")
    created = models.DateTimeField(auto_now_add=True , null = False, blank=False)
    updated = models.DateTimeField(auto_now_add=True , null = False, blank=False)
    class Meta:
        managed = False
        db_table = 'PA001_PostGis_imagefile'


class Pa001PostgisLinkurl(models.Model):
    id = models.BigAutoField(primary_key=True)
    nombre = models.CharField(max_length=255)
    description = models.TextField()
    url = models.URLField(blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True , null = False, blank=False)
    updated = models.DateTimeField(auto_now_add=True , null = False, blank=False)

    class Meta:
        managed = False
        db_table = 'PA001_PostGis_linkurl'


class Pa001PostgisMeteouploadfile(models.Model):
    id = models.BigAutoField(primary_key=True)
    id_gpp = models.CharField(max_length=30)
    f_name = models.CharField(max_length=255)
    file = models.FileField(upload_to="" , null = False, blank=False)
    created = models.DateTimeField(auto_now_add=True , null = False, blank=False)
    updated = models.DateTimeField(auto_now_add=True , null = False, blank=False)

    class Meta:
        managed = False
        db_table = 'PA001_PostGis_meteouploadfile'


class Pa001PostgisMyuploadfile(models.Model):
    id = models.BigAutoField(primary_key=True)
    id_gpp = models.CharField(max_length=30)
    f_name = models.CharField(max_length=255)
    file = models.FileField(upload_to="" , null = False, blank=False)
    created = models.DateTimeField(auto_now_add=True , null = False, blank=False)
    updated = models.DateTimeField(auto_now_add=True , null = False, blank=False)

    class Meta:
        managed = False
        db_table = 'PA001_PostGis_myuploadfile'


class Pa001PostgisPoints(models.Model):
    id = models.BigAutoField(primary_key=True)
    nombre = models.CharField(max_length=255)
    latitud = models.FloatField()
    longitud = models.FloatField()
    description = models.CharField(max_length=250)
    created = models.DateTimeField(auto_now_add=True , null = False, blank=False)
    updated = models.DateTimeField(auto_now_add=True , null = False, blank=False)

    class Meta:
        managed = False
        db_table = 'PA001_PostGis_points'


class Pa001PostgisResultfile(models.Model):
    id = models.BigAutoField(primary_key=True)
    id_gpp = models.CharField(max_length=30)
    f_name = models.CharField(max_length=255)
    file = models.FileField(upload_to="" , null = False, blank=False) 
    type_file = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True , null = False, blank=False)
    updated = models.DateTimeField(auto_now_add=True , null = False, blank=False)

    class Meta:
        managed = False
        db_table = 'PA001_PostGis_resultfile'

P002_Deltares/PA005_Maps/models.py
from django.db import models

# Create your models here.

P002_Deltares/PA005_Maps/forms.py
from django import forms
from PA001_Deltares.models import Pa001PostgisPoints

class PointsForm(forms.ModelForm):
    class Meta:
        model=Pa001PostgisPoints
        fields=['nombre','latitud','longitud','description'
                
                ]
                    

P002_Deltares/PA005_Maps/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
#from PA001_Deltares.models import Pa001PostgisPoints
from .forms import PointsForm

# Create your views here.
    
def datos(request):
    msgerror = 0          
    if request.method=="POST":                
        form = PointsForm(request.POST)
        if form.is_valid():
            form.save()
        return redirect("Maps")
    else:             
        form = PointsForm()
        
    return render(request,"PA005_Maps/mapsCreate.html", {'form': form})

P002_Deltares/templates/PA005_Maps/codigo.html
<script>
    mapboxgl.accessToken = 'TU_CLAVE_DE_ACCESO_MAPBOX'; // Reemplaza con tu clave de acceso
  
    navigator.geolocation.getCurrentPosition(successLocation, errorLocation, {
      enableHighAccuracy: true
    });
  
    function successLocation(position) {
      const longitude = position.coords.longitude;
      const latitude = position.coords.latitude;
  
      const map = new mapboxgl.Map({
        container: 'map',
        style: 'mapbox://styles/mapbox/streets-v11',
        center: [longitude, latitude],
        zoom: 12
      });
  
      map.on('load', function () {
        map.addLayer({
          id: 'places',
          type: 'circle',
          source: {
            type: 'geojson',
            data: {
              type: 'FeatureCollection',
              features: [
                {
                  type: 'Feature',
                  properties: {},
                  geometry: {
                    type: 'Point',
                    coordinates: [longitude, latitude]
                  }
                }
              ]
            }
          },
          paint: {
            'circle-radius': 10,
            'circle-color': '#3887be'
          }
        });
  
        // Geocodificación inversa
        map.on('click', 'places', function (e) {
          const coordinates = e.features[0].geometry.coordinates.slice();
          const locationNameElement = document.getElementById('locationName');
  
          // Obtener el nombre del lugar con la API de geocodificación inversa de Mapbox
          fetch(`https://api.mapbox.com/geocoding/v5/mapbox.places/${coordinates[0]},${coordinates[1]}.json?access_token=${mapboxgl.accessToken}`)
            .then(response => response.json())
            .then(data => {
              const locationName = data.features[0].place_name;
              locationNameElement.textContent = `Nombre del lugar: ${locationName}`;
            });
        });
  
        map.on('mouseenter', 'places', function () {
          map.getCanvas().style.cursor = 'pointer';
        });
  
        map.on('mouseleave', 'places', function () {
          map.getCanvas().style.cursor = '';
        });
      });
    }
  
    function errorLocation() {
      console.log('Unable to retrieve your location');
    }
  </script>
  

P002_Deltares/templates/PA005_Maps/maps.html
{% extends "PA001_Deltares/base.html" %}

{% load static %}

{% block content %}
<head>
  <meta charset="utf-8">
  <title>Add 3D terrain to a map</title>
  <meta name="viewport" content="initial-scale=1,maximum-scale=1,user-scalable=no">
  <link href="https://api.mapbox.com/mapbox-gl-js/v2.14.1/mapbox-gl.css" rel="stylesheet">
  <script src="https://api.mapbox.com/mapbox-gl-js/v2.14.1/mapbox-gl.js"></script>
  <style>
  body { margin: 0; padding: 0; }
  #map { position: absolute; top: 0; bottom: 0; width: 100%; }
  </style>
  </head>
  <body>
  <div id="map"></div>
   
  <script>
    mapboxgl.accessToken = 'pk.eyJ1IjoibWZ1ZW50ZXNhZ3VpbGFyIiwiYSI6ImNsb3NpeXduZzAweHkyaWxsazEzNDFtZmIifQ.7JDeB6ht_cYYH6uPzEBC9Q';
  const map = new mapboxgl.Map({
  container: 'map',
  zoom: 14,
  center: [-114.26608, 32.7213],
  pitch: 80,
  bearing: 41,
  // Choose from Mapbox's core styles, or make your own style with Mapbox Studio
  style: 'mapbox://styles/mapbox/satellite-streets-v12'
  });
   
  map.on('style.load', () => {
  map.addSource('mapbox-dem', {
  'type': 'raster-dem',
  'url': 'mapbox://mapbox.mapbox-terrain-dem-v1',
  'tileSize': 512,
  'maxzoom': 14
  });
  // add the DEM source as a terrain layer with exaggerated height
  map.setTerrain({ 'source': 'mapbox-dem', 'exaggeration': 1.5 });
  });
  </script>
   
  </body>
{% endblock %}

P002_Deltares/templates/PA005_Maps/mapsCreate.html
{% extends "PA001_Deltares/base.html" %}

{% load static %}

{% block content %}
 
<head>
    <meta charset="UTF-8">
    <title>Create Points</title>
    
    <link href='https://api.mapbox.com/mapbox-gl-js/v2.7.0/mapbox-gl.css' rel='stylesheet' />    
    <link rel="stylesheet" href="https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-geocoder/v4.7.0/mapbox-gl-geocoder.css" type="text/css"/>
    <link href="https://unpkg.com/mapbox-gl@2.6.1/dist/mapbox-gl.css" rel="stylesheet">
    
    <script src='https://api.mapbox.com/mapbox-gl-js/v2.7.0/mapbox-gl.js'></script>
    <script src="https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-geocoder/v4.7.0/mapbox-gl-geocoder.min.js"></script>
    
    <link href='https://api.mapbox.com/mapbox-gl-js/v2.6.1/mapbox-gl.css' rel='stylesheet' />

	<script src="https://cdn.jsdelivr.net/npm/es6-promise@4/dist/es6-promise.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/es6-promise@4/dist/es6-promise.auto.min.js"></script>
    <script src="https://unpkg.com/mapbox-gl@2.6.1/dist/mapbox-gl.js"></script>
    <link rel="stylesheet" href="{% static 'PA001_Deltares/css/maps.css' %}">

</head>
<body>
    <h4 style="color: white;">Create Points</h4>
    <form method="post" enctype="multipart/form-data" style="color: white;">
        <div class="form-group" style='padding: 2em'>  
            {% csrf_token %}
                       
                <div class="col-md-10" style='text-align: right'>
                    <label for="id_nombre">    Name:</label> <input type="text" name="nombre" maxlength="255" required id="id_nombre">
                    <label for="id_latitud">  Latitude:</label> <input type="number" name="latitud" step="any" required id="id_latitud">
                    <label for="id_longitud">Length:</label> <input type="number" name="longitud" step="any" required id="id_longitud">
                    <label for="id_description"> description:</label> <input type="text" name="description" maxlength="255" required id="id_description">
                </div>
                <div id='map'>
                    <script src="{% static 'PA001_Deltares/js/maps.js' %}"></script>                                                                              
                </div>
                <input type="submit" value="Save" style="margin-left: 968pt;">  
        </div>    
    </form>
    <script> var geocoder = new MapboxGeocoder({accessToken: mapboxgl.accessToken, mapboxgl: mapboxgl,}); map.addControl(geocoder, 'top-left'); </script>
    <script src="https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-geocoder/v4.7.0/mapbox-gl-geocoder.min.js"></script>
	<script src="https://cdn.jsdelivr.net/npm/es6-promise@4/dist/es6-promise.min.js"></script>
	<script src="https://cdn.jsdelivr.net/npm/es6-promise@4/dist/es6-promise.auto.min.js"></script>
    
</body>

{% endblock %}